name: flutter_cubit_clean_arch
description: "Flutter Base Project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.6.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.2.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0

flutter:
  generate: true
  uses-material-design: true
